### ISSUE TITLE
Good Practice / Recommended?

### ISSUE THREAD

**Issue by bobemoe** [yceruto/symfony-ddd-skeleton#12]
From the official documentation:

> Creating applications with multiple kernels is no longer recommended by Symfony. Consider creating multiple small applications instead. - https://symfony.com/doc/4.4/configuration/multiple_kernels.html

Is that stating that this "virtual kernel" method is no longer recommended, or is this method actually creating "small applications"?  Sorry I'm a bit lost with the terminology here.

**Comment by yceruto** [comment]
There are different opinions and points of view related to this topic. I have been using this approach for a while and it works nicely so far.

The official documentation recommend multiples small apps, well, that's what this skeleton provides, just one kernel that remove boilerplate code between small apps while sharing dependencies, config, src, etc.

I'd recomend this approach for small and medium projects, for big projects I'd use separate apps (microservices).
