### ISSUE TITLE
Problem with prod environment

### ISSUE THREAD

**Issue by alterphp** [yceruto/symfony-ddd-skeleton#19]
Hi @yceruto,

I've just upgraded a multi-kernel application from Symfony 4.4 to 5.3. I use multi-kernel in order to use 2 separate easy_admin configurations.

Everything works as expected in **dev** environment, but **prod** environment looks weird. I log into **admin** (`APP_NAME=main`), then log to **extranet** (`APP_NAME=extranet`), then request the `main` kernel, but it has **extranet** configuration loaded (routing, easy_admin config).

The only difference with your skeleton is that I do not use env var in web context :

```
<?php

declare(strict_types=1);

use App\Kernel;

require_once \dirname(__DIR__).'/vendor/autoload_runtime.php';

return static function (array $context) {
    // Virtal Kernel
    $appName = strpos($context['REQUEST_URI'], '/extranet') === 0 ? 'extranet' : 'main';

    return new Kernel($context['APP_ENV'], (bool) $context['APP_DEBUG'], $appName);
};

```

Any idea of what could go wrong on my side ?

**Comment by alterphp** [comment]
My problem seems resolved by differenciating containerClass in the `Kernel` class :
```
    protected function getContainerClass()
    {
        return ucfirst($this->name).parent::getContainerClass();
    }
```

I don't know why yet...

**Comment by alterphp** [comment]
In some contexts (cache management), Symfony seems to directly associate `kernel.container_class` with `kernel.project_dir`, not with `kernel.cache_dir` nor `kernel.build_dir`.

`kernel.project_dir` is not unique to each kernel AFAIK. Maybe it is part of the solution...

cf. https://github.com/symfony/symfony/blob/a5fa6e5c2aed5fa928493bbe0c8c2df614e9d71d/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L1031

**Comment by yceruto** [comment]
Hi @alterphp 

I will update the template to take this into account. Thanks!
