### ISSUE TITLE
Several questions for things I noticed on getting started

### ISSUE THREAD

**Issue by chapterjason** [yceruto/symfony-ddd-skeleton#26]
Hey @yceruto, thanks for this great skeleton and maker bundle.

I just started using this and want to getting more into separated structures.
I noticed several things on getting started:

- ~The current version of Symfony is 6.0 (this skeleton starts with 5.4)~
  - ~I upgraded to 6.0 as described in the [documentation of Symfony](https://symfony.com/doc/current/setup/upgrade_major.html), works with `-W` and updating also the dependencies, cause of a locked dependency with the maker-bundle.~
  - ~Recipes updates should be done carefully, cause the default Kernel and the route.yaml config are in a different place and initializing the project with `composer create-project yceruto/symfony-skeleton .` doesn't create a git repository. As the `recipe:update` command uses git and patches to apply recipes it was confusing cause the files got detected as removed.~
    - ~`kernel.php` -> Wasn't that complicated, the kernel the skeleton offers specially "context"-aware methods as the default kernel from the recipe is almost empty (Expect for the `MicroKernelTrait`) and I think there aren't any things to change?~
        ~~*I still haven't run it*, but noticed also that the `configureContainer` and `configureRoutes` aren't used. It looks like the signature changed in the MicroKernelTrait? I'am not sure.~~ It is fine, haven't looked properly.
    - ~`routes.yaml` changed a bit and I adjusted the `../src/Kernel.php` to `../../Kernel.php` (which binds the default app context to the Kernel? Not sure if this is wanted. Wouldn't be better to keep the root route.yaml and bind each context folder separately? Or at least the kernel.)~

            diff --git a/config/routes.yaml b/config/routes.yaml
            --- a/config/routes.yaml
            +++ b/config/routes.yaml
            @@ -1,3 +1,7 @@
            -#index:
            -#    path: /
            -#    controller: App\Controller\DefaultController::index
            +controllers:
            +    resource: ../src/Controller/
            +    type: annotation
            +
            +kernel:
            +    resource: ../src/Kernel.php
            +    type: annotation
- I created a PR for the symfony upgrade #27 :)
- I had a diff in the `services.yaml` on the upgrade which was a bit confusing as I noticed the default excludes.
  The default excludes https://github.com/yceruto/symfony-ddd-skeleton/blob/42c5e889447f56785672e4a26ccd1ce9a57b499a/config/services.yaml#L18-L20 doesn't make sense after reading the README.md https://github.com/yceruto/symfony-ddd-skeleton/blob/42c5e889447f56785672e4a26ccd1ce9a57b499a/src/Module/SubModule/Domain/README.md?plain=1#L9 Shouldn't services still be autoloaded?
- Is there an example project which have an example for all the possible usages, like described in the README.md files?
- I think there is an issue with the maker-bundle, the other commands as described in the README are missing:

      ❯ symfony console | grep ddd                     
      make:ddd:context            Creates a new Kernel context (Application)

  Update 6. May 2022: I found the issue on this case. Created a PR to fix this https://github.com/yceruto/micro-symfony/pull/2

         - yceruto/micro-symfony[v1.0.0, ..., v1.0.1] require symfony/http-kernel ^5.4 -> found symfony/http-kernel[v5.4.0, ..., v5.4.8] but these were not loaded, likely because it conflicts with another require.
         - yceruto/ddd-maker-bundle v1.2.4 requires yceruto/micro-symfony ^1.0 -> satisfiable by yceruto/micro-symfony[v1.0.0, v1.0.1].
         - Root composer.json requires yceruto/ddd-maker-bundle ^v1.2.4 -> satisfiable by yceruto/ddd-maker-bundle[v1.2.4].
 
- Does it make sense to create a template folder in each context which have a twig presentation? Like this (works btw)

      # context/app/config/packages/twig.yaml
      twig:
          default_path: '%kernel.project_dir%/templates'
          paths:
              '%kernel.project_dir%/context/app/templates': App
    
      when@test:
          twig:
              strict_variables: true

Cheers! 😁

**Comment by yceruto** [comment]
Hi @chapterjason thank you for taking care of checking this, I will be back soon to check each point!

**Comment by chapterjason** [comment]
@yceruto Created a PR for the Symfony upgrade. But first I think we should adjust the maker dependency, already created a PR there too.

**Comment by yceruto** [comment]
> I had a diff in the services.yaml on the upgrade which was a bit confusing as I noticed the default excludes.
The default excludes ... Shouldn't services still be autoloader?

I removed the exclusion config to allow autowiring/autoconfiguring available ports defined under the Domain directory. That's the case for example the Repository interface or Domain services.

**Comment by yceruto** [comment]
> Is there an example project which have an example for all the possible usages, like described in the README.md files?

I plan to do it but it's not open-source right now.

**Comment by yceruto** [comment]
> I think there is an issue with the maker-bundle, the other commands as described in the README are missing:

It should ok now.

**Comment by yceruto** [comment]
> Does it make sense to create a template folder in each context which have a twig presentation? Like this (works btw)

It's up to you, you can use Twig or Serializer to render the response. But it's not the template goal to provide that specification. I would like to keep it as generic as possible.

**Comment by chapterjason** [comment]
> > I had a diff in the services.yaml on the upgrade which was a bit confusing as I noticed the default excludes.
> > The default excludes ... Shouldn't services still be autoloader?
> 
> I removed the exclusion config to allow autowiring/autoconfiguring available ports defined under the Domain directory. That's the case for example the Repository interface or Domain services.

Ouh, yes, didn't noticed that.

> > Is there an example project which have an example for all the possible usages, like described in the README.md files?
> 
> I plan to do it but it's not open-source right now.

Ahh okay, struggle a bit to understand how the actual data flow is from a console command in the context to the database. Which dto's I use where? Where do I validate the dto/entity? And more ... 

I really would like to help if there is anything available to find answers to all the use cases.

> > I think there is an issue with the maker-bundle, the other commands as described in the README are missing:
> 
> It should ok now.

Works great now, now I can try the maker. 👍🏼 


I think this solved all my questions. 😄 Thanks!
