### ISSUE TITLE
Vendors

### ISSUE THREAD

**Issue by stevro** [yceruto/symfony-ddd-skeleton#7]
How can I install two different versions of same vendor using this structure?

**Comment by yceruto** [comment]
Hi @stevro, what do you mean with "two different versions of same vendor"?

If you're refering to two different versions of the same package/dependecy then I think that is not possible without two composer.json and so two different projects (autoload.php).

This structure represents a project with multiple app/kernel (virtual apps) but all related to the same vendors.
